// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCpVNJiirDzpk-l0xQl8ukCT44XSREz4c',
    appId: '1:39164524560:web:0190082abfc24db96cb295',
    messagingSenderId: '39164524560',
    projectId: 'food-ingredient-recognition',
    authDomain: 'food-ingredient-recognit-2d83a.firebaseapp.com',
    storageBucket: 'food-ingredient-recognition.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwaFhTyGmq6G1lKzul74whDjdQ0Yxg4Cg',
    appId: '1:39164524560:android:f5c77b442643ec346cb295',
    messagingSenderId: '39164524560',
    projectId: 'food-ingredient-recognition',
    storageBucket: 'food-ingredient-recognition.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFxBxTEbHSe_VPcC0efejwhNqwSTsc1gg',
    appId: '1:39164524560:ios:a9ba9ebeef3de1f36cb295',
    messagingSenderId: '39164524560',
    projectId: 'food-ingredient-recognition',
    storageBucket: 'food-ingredient-recognition.firebasestorage.app',
    iosBundleId: 'com.example.fypWyc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFxBxTEbHSe_VPcC0efejwhNqwSTsc1gg',
    appId: '1:39164524560:ios:a9ba9ebeef3de1f36cb295',
    messagingSenderId: '39164524560',
    projectId: 'food-ingredient-recognition',
    storageBucket: 'food-ingredient-recognition.firebasestorage.app',
    iosBundleId: 'com.example.fypWyc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCpVNJiirDzpk-l0xQl8ukCT44XSREz4c',
    appId: '1:39164524560:web:3962223b7116ce896cb295',
    messagingSenderId: '39164524560',
    projectId: 'food-ingredient-recognition',
    authDomain: 'food-ingredient-recognit-2d83a.firebaseapp.com',
    storageBucket: 'food-ingredient-recognition.firebasestorage.app',
  );
}
